#!/bin/bash

# Config
username="myuser"
password="mypass"
posturl="http://yourhost.tld/gtkgrab/handler.php"

# Filename is supplied as command line argument
filename="$1"

# Add border and shadow
convert $filename -bordercolor white -border 13 \
                  \( +clone -background black -shadow 80x3+2+2 \) +swap \
                  -background white -layers merge +repage /tmp/screenshot.png

# Upload image
data=$(cat /tmp/screenshot.png | base64)
hash=$(echo -n "$data$password" | sha1sum | cut -d' ' -f1)

url=$( \
    echo -n "$data" | \
        curl --header "X-Username: $username" \
             --header "X-Signature: $hash" \
             --header "Content-Type: text/plain" \
             --data-binary "@-" \
             "$posturl" \
)

rm /tmp/screenshot.png

# Copy URL to clipboard and notify the user
echo -n "$url" | xclip -selection c
notify-send --hint=int:transient:1 "Screenshot Uploaded" "Copied URL to clipboard:\n$url"
